server:
    port: 8001
spring:
    application:
        name: user-service
    datasource:
        url: jdbc:mysql://${DATASOURCE_HOST:localhost}:3306/twitter-user?createDatabaseIfNotExist=true
        username: root
        password: 123456
        driverClassName: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL8Dialect
    sql:
        init:
            mode: always
            data-locations: classpath:sql-test/clear-user-db.sql, classpath:sql-test/populate-user-db.sql
    kafka:
        bootstrap-servers: localhost:9092
        consumer:
            group-id: user-test
eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka
        fetch-registry: true
        register-with-eureka: true
    instance:
        hostname: localhost
